### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by koval01** [SpigotPlugins-xuancat0208/FartherViewDistance#2]
Update this plugin please for 1.19.2

**Comment by xuancat0208** [comment]
1.19.1 and 1.19.2 use exactly the same thing, so can be directly used

**Comment by koval01** [comment]
9.7.3 didn't start on 1.19.2, now I can't start 9.7.4
You missed 1.19.2, create a separate build for it please
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/61350874/207182344-2435fe71-786a-45d2-9b83-ab0d31d188cc.png">

**Comment by xuancat0208** [comment]
Your configuration is wrong... As the message given, X21 mode is not, please use X31 or X15

**Comment by koval01** [comment]
Give please 9.7.3 version
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/61350874/207385318-4194b9c9-4387-41f5-a425-66afbec571e9.png">
