### ISSUE TITLE
ERROR 1.19.3

### ISSUE THREAD

**Issue by Darkseno** [SpigotPlugins-xuancat0208/FartherViewDistance#3]
Hello,

I'm using the last build 1.19.3 of purpur and the last version of Farther but when a player connects to the server, some errors appear

https://pastebin.com/5GvQdesK

Good day to you

**Comment by xuancat0208** [comment]
no no no, 9.7.4 Support 1.19.3 (Deprecat 1.19.1 and 1.19.2), you need use 9.7.3

**Comment by Darkseno** [comment]
Oh sorry my baaaaaaaaaaaad
